# Generated by Django 2.2 on 2021-12-28 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestStudioCore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairepassanswer',
            name='questionnaire_pass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='TestStudioCore.QuestionnairePass'),
        ),
    ]
